services:
  aghanims-receipt-generator:
    image: ghcr.io/abdallahdalvi/receipter:latest
    container_name: aghanims-receipt-generator
    restart: unless-stopped
    ports:
      - "9009:3000"
    environment:
      - PORT=3000
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
